module.exports = {
    JOIN_ROOM: 'JOIN_ROOM',
    CREATE_ROOM: 'CREATE_ROOM',
    UPDATE_ROOMS: 'UPDATE_ROOMS',
    ACK: 'ACK',
    SET_PLAYER_DATA: 'SET_PLAYER_DATA',
    UPDATE_PLAYER: 'UPDATE_PLAYER',
};
